name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install black
    - name: Lint with black
      run: |
        ls
        /home/runner/.local/bin/black . -l 120 --check

